### ISSUE TITLE
Support all Cassandra data types

### ISSUE THREAD

**Issue by milliondreams** [tuplejump/FiloDB#23]
We should be able to support all cassandra data data types. I am specially looking for -

1. All the numeric types (BigInt, Float, Decimal ,etc.)
2. Timestamp
3. UUID (and special support for TimeUUID)

**Comment by velvia** [comment]
Started working on Filo (as opposed to FiloDB), the underlying columnar format, to support different types, and to make sure the wire format is stable and future and change compatible going forward.

**Comment by milliondreams** [comment]
Should we bring in that  (the Filo code) in the same repo.

**Comment by velvia** [comment]
I’d prefer to keep it separate.   It can be used outside of FiloDB, and is a library.   I’m hoping to have some other projects use it.

**Comment by milliondreams** [comment]
We can have it as a subproject and still publish it ass library, wouldn't that simplify working with the project?
