### ISSUE TITLE
Automate ingestion/etl from cassandra column family to FiloDB

### ISSUE THREAD

**Issue by milliondreams** [tuplejump/FiloDB#24]
My intention here is to conceptually use FiloDB as an index for a Cassandra Table so it becomes more transparent to users/application writers and can be used with existing applications to give them the analytics boost.

From Blender perspective, for now this is the easiest and most straightforward way to work on our storage optimizer and fits in the current blender system without much change.

**Comment by trulite** [comment]
How do I ingest to Filo?

satya [12:38 PM]
From inside the C* process

satya [12:40 PM]
Assuming I treat Filo as a library inside C*. I have the following questions

satya [12:41 PM]
1. How will the Filo coordinator be setup? Is there a way to lazy setup when I create a C* secondary index? Does this require us to hook into C* startup process?

satya [12:43 PM]
2. The 2i approach means every write on a C* table is replicated into 'replication factor’ number of nodes. If each of these nodes have Filo embedded and write the same row, how does it affect the underlying replication on Filo Columnstore C* tables

satya [12:44 PM]
3. The 2i approach will probably need a different Column store implementation which will write to just local nodes using C* server local API. Does this sound like a viable approach? (edited)
