### ISSUE TITLE
Upgrade to Spark 1.6

### ISSUE THREAD

**Issue by velvia** [tuplejump/FiloDB#61]
Here are the new features:

https://docs.cloud.databricks.com/docs/spark/1.6/index.html#Apache%20Spark%201.6%20Release%20Notes.html

Of particular relevance:

* https://issues.apache.org/jira/browse/SPARK-11778 - DataFrame `sqlContext.read.table("dbName.tableName")`
* https://issues.apache.org/jira/browse/SPARK-10978 - avoiding double filters in Spark SQL.  This way partition key predicates won't cause Spark to load those columns for filtering again - which is a waste, unless the partition column is computed (ex `:stringPrefix` - in which case Spark should probably filter again)

**Comment by velvia** [comment]
Also, for Spark 2.0, vectorization looks really neat:

https://github.com/apache/spark/pull/11055

**Comment by vgromakowski** [comment]
+1 for spark upgrade

**Comment by jonbuffington** [comment]
@velvia We are currently using 1.6.1 and looking toward 2.0. Do you have a sense of where this sits in the priority queue?

We just started looking at FiloDB and do not yet have a sense of whether we could effectively contribute to this ticket. Do you have a effort guess?

**Comment by velvia** [comment]
Hi!   Hmm, 2.0 is not that high right now because 1.5/1.6 seems to run fine, 2.0 is not out yet and has bigger API changes.

Merging 1.6 support could happen soon though, as 1.6 seems to be running OK, but would like to test it out more at scale first.

If you are asking about effort for a 1.6 port, I can tell you it is just a one-line change — change the sparkVersion line in build.sbt, that’s it  :)    All the tests pass.

2.0 - I’m not sure.   This is where some help would be awesome - try building against 2.0 and see what breaks.  I would anticipate the InternalRow stuff that we rely on for high speed scans to have changed, so that would be more work to port.

**Comment by jonbuffington** [comment]
@velvia Thanks for the quick reply! 1.6 would is our current target. I was planning to make the change you suggested locally shortly.

I was waiting for 2.0 to be RC-ish. I should be more familiar with FiloDB by then and will report back what I find.

**Comment by velvia** [comment]
@jonbuffington 1.6 support has just been merged!

I'm keeping this ticket open for a tiny bit as there are other small enhancements listed here.

**Comment by jonbuffington** [comment]
@velvia Thanks! I will pull the changes tomorrow.

**Comment by velvia** [comment]
Turns out SPARK-11778 is not relevant, and SPARK-10978, while we could implement it, would probably not benefit most queries since most schemas in FiloDB use computed functions.  I might still implement it, but we'll see.  So closing.
