### ISSUE TITLE
Table schema is overwritten by input dataframe schema during ingestion 

### ISSUE THREAD

**Issue by parekuti** [tuplejump/FiloDB#72]
![screen shot 2016-03-08 at 11 17 31 am](https://cloud.githubusercontent.com/assets/7152169/13607989/ba1ad05e-e520-11e5-9389-3f74f6e3f31d.png)
![screen shot 2016-03-08 at 11 21 15 am](https://cloud.githubusercontent.com/assets/7152169/13608013/d6abb666-e520-11e5-8bfd-2a9d958e5021.png)

**Comment by velvia** [comment]
Hi @parekuti, could you paste your ingestion code?   The schema will get overwritten if `SaveMode.Overwrite` is used.

**Comment by parekuti** [comment]
Yes, i am using ```SaveMode.Overwrite```. Here is the code snippet.

```srcDF.write().format("filodb.spark").option("dataset",targetTable).
				    option("row_keys", "consolidated_billing_source_cd,security_level,charge_type_desc,charge_cd,asset_id,billing_invoice_id,billing_invoice_line_num").
				    option("segment_key", ":string /0").
				    option("partition_keys", "corp_code,fleet_number,ge_fiscal_period_name").
				    mode(SaveMode.Overwrite).save();```

**Comment by velvia** [comment]
@parekuti this behavior is the default right now - when Overwrite mode is on the dataset definition can be changed.  Going to merge this with #67 and make the default to NOT change the definition.
