### ISSUE TITLE
Control commits to table via memtable flush

### ISSUE THREAD

**Issue by venugopalrp** [tuplejump/FiloDB#77]
For certain work loads it is important to commit all the writes to FiloDB tables at the end of ETL process. Currently there is no documented option that allows programmer to issue a commit at the end of ETL to trigger flush of any pending memtable data to tables.

Another option is to control memtable flushes if there are no further writes to memtable in past X minutes/secs.

**Comment by velvia** [comment]
In master there is now an option in Spark called `flush_after_write`, which defaults to true.  Basically that means at the end of each INSERT INTO or `insertIntoFilo` or `dataFrame.write...`, then a flush will be explicitly issued.   However it can be turned off for streaming workloads.

I'll open a separate issue for time-based memtable flushes, which is a great idea.
