### ISSUE TITLE
Error when try to execute StreamingTest

### ISSUE THREAD

**Issue by jose1003** [tuplejump/FiloDB#83]
When I try to execute test Streaming test, I get this error
Error:scalac: Class org.apache.avro.reflect.Stringable not found - continuing with a stub.

**Comment by velvia** [comment]
Hm that's really weird.  Are you trying to run with a different version of scala?

**Comment by velvia** [comment]
@jose1003 do you still see this with latest master?

**Comment by velvia** [comment]
Going to close, not seeing anything like that.   I think it's an environmental error.
