### ISSUE TITLE
ambiguous licence position

### ISSUE THREAD

**Issue by fommil** [tuplejump/FiloDB#85]
You depend on https://github.com/outworkers/phantom which is licenced under a [dubious proprietary licence](https://github.com/outworkers/phantom/blob/19e3020793f99fbeab87a3c3bb98d8158fa6914f/LICENSE.txt) including such gems as

"You may not publish any tutorials or educational material on phantom, any blog posts or any written published content on phantom without our explicit written consent."

and

"any new clause provided by future updates of this license will apply to all existing versions of phantom irrespective of any timeframe."

Indeed several members of the scala community have received takedown notices of their blog articles.

Explicitly noting in https://github.com/outworkers/phantom#license-and-copyright that "it is **not** provided under an OSS license." (emphasis mine)

**Comment by velvia** [comment]
Phantom has been removed.

**Comment by fommil** [comment]
Congratulations!
