### ISSUE TITLE
Is ByteIteratorColumn from phantom in use anywhere?

### ISSUE THREAD

**Issue by alexflav23** [tuplejump/FiloDB#87]
Hi @velvia,

I just wanted to ask if the `ByteIterator` functionality from phantom is of any use whatsoever to you anymore. There's a lot of code we ported in from Akka that we don't really want to maintain and as I recall you took a different approach in the end, so there may be 0 reason for us to keep it in the codebase.

Also, you can extend and create your own columns quite easily, and perhaps that's why it makes little sense to do keep it all in one place, especially since are doing nothing but duplicating already existing concerns far better addressed in different projects.

Regards.

**Comment by velvia** [comment]
HI Flavian, go ahead and remove it.   We decided to use scodec.bits.ByteVector instead.   Thanks!

**Comment by alexflav23** [comment]
Thanks for letting me know!
