### ISSUE TITLE
Clustering support

### ISSUE THREAD

**Issue by velvia** [tuplejump/FiloDB#90]
Currently, FiloDB is a jar/library used in Spark for both ingestion and reading.  For ingestion each node / worker in Spark holds a FiloDB memtable.  However, they are currently all independent and do not communicate with one another, and furthermore do not communicate with the driver.  This will have to change.

* We want to be able to poll each memtable for current status
* We want to be able to command each memtable to flush, and get errors back
* Certain operations really require some coordination.  For example, truncating or deleting a dataset cannot safely be done without coordinating with all nodes to ensure there aren't memtables for a given dataset still in session.
* Properly supporting a distributed in-memory column store will require coordination
* It would be nice for clients to be able to monitor the memtable state, externally or internally
* This is secondary concern, but we might want to implement our own mechanism so the user doesn't have to sort data themselves, but rather exchange incoming records such that data is partitioned by token range for local fast writes

Ideally, we want this clustering mechanism to be
* Independent of Spark, especially Spark internals (for example, in the future we can enable users who want to use FiloDB purely as a library to do that, without needing Spark... or for direct Kafka to FiloDB connection)
* Flexible for a variety of use cases
* Enable different communication patterns, as evidenced by the different use cases above

I'm leaning towards using Akka cluster, with the default TCP connectivity as a first cut.  This would require a separate port, but the huge advantage would be it would be able to easily meet all of the goals above.  Also, because all communication is designed around the NodeCoordinatorActor, an Actor-based mechanism is preferable.  Some other alternatives:

1. Spark has an internal Akka-based communication mechanism.  It only works for driver to worker communication,  and is being phased out in 2.0.
2. Layer Akka clustering/remote over Spark internal mechanism

In the future, we could explore using faster network mechanisms such as Aeron (https://github.com/real-logic/Aeron).

I'd love to hear feedback from @trulite @helena and others.

**Comment by velvia** [comment]
@java8964 what do you think of requiring an extra port to be used between Spark workers and driver for this?

**Comment by java8964** [comment]
Sorry, I kind of not sure what this "extra port" means. My understand is that current Spark and FiloDB both use "Akka", and Spark 2.0 is phasing out it.

My question is do you know what comminution channels in Spark 2.0 to replace "Akka". For us, or for whoever already deployed Spark + C*, it will be a concern introducing another part into it. I don't know too  much about Akka cluster, but will it be used just as a library, or need separated setup in the cluster? Adding an extra port is not a big deal, as normally these nodes in cluster already in LAN, but having something totally new in the stack is quite a new question. Can this part still reuse what is available in Spark 2.0, or at least make it a plugin in Architecture?

Yong

**Comment by velvia** [comment]
The architecture would not change.  You would still have FiloDB as a jar, it would sit in all of the Spark app’s executors, as well as the driver.  Akka cluster is just another library in the FiloDB jar (today we already use Akka, just not clustering).

The change would be that the FilodB jar components from different executor nodes and the driver would talk to each other via an extra port, which you would open in the LAN.  

Rest of the deploy would be identical to today.

As far as Spark 2.0 I believe Akka will be replaced with Netty.   To reuse that Netty connection would probably require a significant change to Spark, one that I’m not sure the committers would be open to.   :(    I could explore using mechanisms such as broadcast etc.

-Evan

**Comment by velvia** [comment]
Merged now.
