### ISSUE TITLE
Lost rows during the same data ingesting into FiloDB

### ISSUE THREAD

**Issue by java8964** [tuplejump/FiloDB#92]
I am testing FiloDB with latest trunk, include PR-91, and  can produce this problem that I saw the filodb lost raw after the data ingested. Below is the test case I run, and just want to make sure that it is a bug, not something I misunderstand how filodb is supposed to work.

I have this 1m records of unique emails, with domain. I will use the first 2 characters as the partition key, and use the domain as the segment key, and unique email address itself as the row key. I tested with in memory.
1) After I save the data from spark into filoDB, if I load the data back in one DF, the count is 1M.
2) Then I save the exactly same data from spark into filoDB again in the same spark shell, and load the data back in one DF, the count is less than 1M.

I enable the log at debug level for filoDB package, and the full log is attached.
From the log, you can see what is my steps, and the log output from filoDB, and the 2nd time, the count is not correct. 

I will also dig the log more, as want to understand more internal of filoDB. Hope the log is helpful to identify the root cause of this case.

Thanks
Yong

[filodb-lost-update-bug.log.gz](https://github.com/tuplejump/FiloDB/files/228873/filodb-lost-update-bug.log.gz)

**Comment by velvia** [comment]
@java8964 so I'm looking at your logs now.  Your choice of segment key probably results in really small segments, btw.

I don't see anything unusual from the logs alone.

Repeating the steps from the other PR, including starting the Spark shell (except I added java options for G1GC), I first verified that all the emails are indeed unique.

I then discovered something in my new code, which breaks the InMemoryColumnStore, so I'll go back and fix that.  But in the meantime, you might want to issue a flush at the end manually and see if that fixes it.

`filodb.spark.FiloSetup.client.flushByName("poc1")`

(Note this API will change slightly in the future)

**Comment by velvia** [comment]
@java8964 I have some changes in a new branch, which adds "clustering" support.
velvia/clustering-support-90

If you run in local / in-memory store, like your test in the other thread, you should find that it consistently returns 1 million rows now.   Basically one change is that it makes sure to flush any remaining rows it finds in the memtable at the end of ingestion.

If you test code in this branch on a cluster, be ware that it will require an extra port to be opened.  Right now the port assignment is random, and I'll need to add config to make sure it's not random.

It will be possible to connect in the future remotely to this port and get monitoring/stats out.

**Comment by velvia** [comment]
Fix is merged now
